name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Build and Deploy
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.PAGE_TOKEN }}
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build 